Allow the user to select the OSP version on which the stack will run
redhat-openstack/openshift-on-openstack pull request #313
Opened 2017-01-26 17:20 UTC by markllama

The bastion host must communicate with the OSP service and gather host information from the other instances.  It uses the `os-collect-config` RPM to configure the communications and collect information.

The location of this package depends on the version of OSP in use.  The OSP RPM repo names change with the OSP version.

This patch allows the caller to set the OSP version so that the templates can install and configure the correct version of the `os-collect-config` package and prepare for operation.

2017-01-31 20:56 UTC, jprovaznik requested changes

2017-01-31 20:56 UTC, jprovaznik commented on collect-config-setup/fragments/install_config_agent_yum.sh
> +
^ this can be deleted

2017-01-31 20:56 UTC, jprovaznik commented on collect-config-setup/fragments/configure_config_agent.sh
> +orc_scripts=/usr/libexec/os-refresh-config
Don't you break backward compatibility with changing the path? You could use symlink to assure that it will keep working with older version.

2017-02-01 15:08 UTC, markllama commented on collect-config-setup/fragments/install_config_agent_yum.sh
> +
Actually it allows a value to be set when testing the script outside of heat.

2017-02-01 15:09 UTC, markllama commented on collect-config-setup/fragments/configure_config_agent.sh
> +orc_scripts=/usr/libexec/os-refresh-config
No, I was already getting deprecation messages when using the old value, indicating that the new one is correct. I also tested with the new value on OSP8 successfully.

2017-02-04 07:50 UTC, jprovaznik commented on collect-config-setup/fragments/configure_config_agent.sh
> +orc_scripts=/usr/libexec/os-refresh-config
ack

2017-02-04 07:56 UTC, jprovaznik commented on openshift.yaml
> +
Could you please set a default value here (and remove the extra newline)? Otherwise it looks like ready to be merged.

2017-02-07 21:53 UTC, markllama commented on openshift.yaml
> +
Done

2017-02-08 08:20 UTC, jprovaznik commented
LGTM, Mark reported that testing this on OSP 8 and 10 was OK, merging this as there is nobody else ATM.

2017-02-08 08:20 UTC, jprovaznik commented
@markllama it would be also nice to add a note into README about posibility to set OCP version (in a followup patch).

2017-02-08 08:20 UTC, merged