enable injection of custom ca cert into trust chain
redhat-openstack/openshift-on-openstack pull request #327
Opened 2017-03-23 15:25 UTC by wrichter

This allows you to enter a trusted ca cert to the openshift nodes and bastion host. This solves the issue https://bugzilla.redhat.com/show_bug.cgi?id=1419182 for me.

To use it, simply add a another parameter to your environment file as such:

  trusted_ca_cert: |
    -----BEGIN CERTIFICATE-----
    <... CERT CONTENT ...>
    -----END CERTIFICATE-----

2017-03-29 12:37 UTC, markllama requested changes
I think the variable name could be 'ca_cert' universally.  All CAs submitted with be "trusted".

When the ca_cert parameter is added to the callout to the loadbalancer resource in openshift.yaml, it then needs to be added to all of the loadbalancer*.yaml as in input parameter.

2017-03-29 12:37 UTC, markllama commented on bastion.yaml
> +  trusted_ca_cert:
Perhaps silly, but aren't all CA's trusted? Can you change this to 'ca_cert' to match the others?  This doesn't need to be the Openstack CA cert, it could be any cert which needs to be placed on every instance.

Thanks!

2017-03-29 12:37 UTC, markllama commented on loadbalancer_dedicated.yaml
> +  trusted_ca_cert:
This parameter must be added to all of the loadbalancer_*.yaml for consistency.

2017-03-29 13:03 UTC, markllama requested changes
Could you add a section to the README for this parameter?

2017-04-03 12:16 UTC, markllama commented
Superceded by PR #332

2017-04-05 11:59 UTC, tomassedovic commented
I'm closing this since the following PR has merged:
https://github.com/redhat-openstack/openshift-on-openstack/pull/333

It has all the changes here plus the docs and everything else @markllama asked for here.

2017-04-05 11:59 UTC, closed without merging